#!/bin/bash

#PBS -N d2q9-bgk
#PBS -j oe
#PBS -o d2q9-bgk.out
#PBS -q teaching
#PBS -l nodes=1:ppn=16:gpus=1,walltime=00:10:00

# Change the working directory (default is home directory)
cd "$PBS_O_WORKDIR"

module load cuda/toolkit/7.5.18

# Select the GPU that we've been allocated
device=$(cat $PBS_GPUFILE)
device=${device#*gpu}
export OCL_DEVICE=$device

echo "Running on host: $(hostname)"
echo "Time is: $(date)"
echo "Directory is: $(pwd)"
echo "PBS job ID is: $PBS_JOBID"
echo "This jobs runs on the following machines: $(cat "$PBS_NODEFILE" | uniq)"
echo "GPU selected: $OCL_DEVICE"
echo

# Run the executable
./d2q9-bgk input_128x128.params obstacles_128x128.dat

